[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="null" type="java.lang.Object" --]
[#-- @ftlvariable name="Session" type="freemarker.ext.servlet.HttpSessionHashModel" --]
[#-- @ftlvariable name="Request" type="freemarker.ext.servlet.HttpRequestHashModel" --]
[#-- @ftlvariable name="RequestParameters" type="freemarker.ext.servlet.HttpRequestParametersHashModel" --]

[#-- @ftlvariable name="math" type="java.lang.Math" --]
[#-- @ftlvariable name="sec" type="org.apache.shiro.SecurityUtils" --]
[#-- @ftlvariable name="sampleCtl" type="com.slyak.controller.SampleCtl" --]

[#-- @ftlroot "tags" --]
[#import '/main.ftl' as main]
[#import '/ui.ftl' as ui]
[#import '/spring.ftl' as spring]
